version: '3'

services:
  angular-frontend:
    build:
      context: ./angular-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"

  node-backend:
    build:
      context: ./node-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  second-backend:
    build:
      context: ./second-backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
